name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  release:
    types: [created]

jobs:
  create-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: |
          npm install
          npm test
        working-directory: .

      - name: Build Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run electron:build
          ls -la
        working-directory: .

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/BrewMate-${{ env.VERSION }}-universal-mac.zip
          draft: false
          name: Release ${{ github.ref }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true

      - name: Generate SHA256 Checksum
        run: |
          shasum -a 256 ./dist/BrewMate-${{ env.VERSION }}-universal-mac.zip | awk '{print $1}' >> shasumver
          echo "SHA 256:" >> $GITHUB_STEP_SUMMARY
          cat shasumver >> $GITHUB_STEP_SUMMARY
