name: Update Homebrew Cask

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  update-cask:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' }}

    steps:
      - name: Checkout BrewMate repository
        uses: actions/checkout@v3
        with:
          repository: romankurnovskii/BrewMate
          path: BrewMate
          token: ${{ secrets.TOKEN_HOMEBREW_CASK || github.token  }}

      - name: Checkout homebrew-cask repository
        uses: actions/checkout@v3
        with:
          repository: romankurnovskii/homebrew-cask
          path: homebrew-cask
          token: ${{ secrets.TOKEN_HOMEBREW_CASK || github.token  }}

      - name: Update cask file
        run: |
          VERSION=$(jq -r .version BrewMate/package.json)
          SHA256=$(cat BrewMate/shasumver)
          CASK_FILE="homebrew-cask/Casks/brewmate.rb"
          sed -i "s/version .*/version \"$VERSION\"/" $CASK_FILE
          sed -i "s/sha256 .*/sha256 \"$SHA256\"/" $CASK_FILE

      - name: Create Pull Request
        run: |
          VERSION=$(jq -r .version BrewMate/package.json)
          BRANCH_NAME=update-version-${VERSION}
          git -C homebrew-cask config user.name "R K"
          git -C homebrew-cask config user.email "email@example.com"
          git -C homebrew-cask checkout -b ${BRANCH_NAME}
          git -C homebrew-cask add .
          git -C homebrew-cask commit -m "update to version ${VERSION}"

          REPO_URL=$(git -C homebrew-cask remote get-url origin)
          REPO_URL_WITH_TOKEN=$(echo "${REPO_URL}" | sed "s://://${TOKEN_HOMEBREW_CASK}@:")
          git -C homebrew-cask remote set-url origin "${REPO_URL_WITH_TOKEN}"

          # Delete the remote branch if it exists
          git -C homebrew-cask push origin --delete ${BRANCH_NAME} || true

          # Push the branch
          git -C homebrew-cask push origin ${BRANCH_NAME}

          # Create PR
          PR_URL="https://api.github.com/repos/romankurnovskii/homebrew-cask/pulls"
          curl --request POST \
          --url $PR_URL \
          --header "authorization: token ${TOKEN_HOMEBREW_CASK}" \
          --header 'content-type: application/json' \
          --data @- << EOF
          {
            "title": "Update BrewMate to ${VERSION}",
            "body": " **${GITHUB_WORKFLOW}**. \n\n commit: _${GITHUB_SHA}_.",
            "head": "${BRANCH_NAME}", 
            "base": "main"
          }
          EOF

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN_HOMEBREW_CASK: ${{ secrets.TOKEN_HOMEBREW_CASK }}
